import { useMemo } from "react";
import { useRides } from "../context/RidesContext";
import { useAuth } from "../context/AuthContext";
import {
  PieChart,
    Pie,
      Cell,
        Tooltip,
          ResponsiveContainer,
            Legend,
              BarChart,
                Bar,
                  XAxis,
                    YAxis,
                      CartesianGrid,
                      } from "recharts";

                      export default function AdminDashboard() {
                        const { rides } = useRides();
                          const { reservations } = useAuth();

                            // ✅ Statistiques globales
                              const totalRides = rides.length;
                                const totalReservations = reservations.length;

                                  const uniqueDrivers = useMemo(() => {
                                      const drivers = new Set(rides.map((r) => r.driver));
                                          return drivers.size;
                                            }, [rides]);

                                              // 📊 Graphique circulaire : trajets par conducteur
                                                const driverData = useMemo(() => {
                                                    const counts = {};
                                                        rides.forEach((r) => {
                                                              counts[r.driver] = (counts[r.driver] || 0) + 1;
                                                                  });
                                                                      return Object.entries(counts).map(([name, value]) => ({ name, value }));
                                                                        }, [rides]);

                                                                          // 📅 Graphique barres : trajets par date
                                                                            const ridesByDate = useMemo(() => {
                                                                                const dateCount = {};
                                                                                    rides.forEach((r) => {
                                                                                          dateCount[r.date] = (dateCount[r.date] || 0) + 1;
                                                                                              });
                                                                                                  return Object.entries(dateCount).map(([date, count]) => ({ date, count }));
                                                                                                    }, [rides]);

                                                                                                      // 🕒 Dernier trajet ajouté
                                                                                                        const lastRide = rides[rides.length - 1];

                                                                                                          const COLORS = ["#22c55e", "#16a34a", "#15803d", "#4ade80", "#86efac"];

                                                                                                            return (
                                                                                                                <div className="min-h-[85vh] bg-green-50 py-10">
                                                                                                                      <div className="container mx-auto px-4">
                                                                                                                              <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
                                                                                                                                        �� Tableau de bord - Administration
                                                                                                                                                </h1>

                                                                                                                                                        {/* ====== STATS PRINCIPALES ====== */}
                                                                                                                                                                <div className="grid md:grid-cols-3 gap-6 mb-10">
                                                                                                                                                                          <div className="bg-white rounded-xl shadow p-6 text-center">
                                                                                                                                                                                      <h2 className="text-3xl font-bold text-green-700">{totalRides}</h2>
                                                                                                                                                                                                  <p className="text-gray-600 mt-2">Trajets disponibles</p>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                      <div className="bg-white rounded-xl shadow p-6 text-center">
                                                                                                                                                                                                                                  <h2 className="text-3xl font-bold text-green-700">{totalReservations}</h2>
                                                                                                                                                                                                                                              <p className="text-gray-600 mt-2">Réservations effectuées</p>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                  <div className="bg-white rounded-xl shadow p-6 text-center">
                                                                                                                                                                                                                                                                              <h2 className="text-3xl font-bold text-green-700">{uniqueDrivers}</h2>
                                                                                                                                                                                                                                                                                          <p className="text-gray-600 mt-2">Conducteurs actifs</p>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                    {/* ====== GRAPHIQUE CIRCULAIRE ====== */}
                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded-xl shadow p-8 mb-10">
                                                                                                                                                                                                                                                                                                                                      <h2 className="text-xl font-semibold text-green-700 mb-4 text-center">
                                                                                                                                                                                                                                                                                                                                                  Répartition des trajets par conducteur
                                                                                                                                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                                                                                                                                      <div className="h-80">
                                                                                                                                                                                                                                                                                                                                                                                  {driverData.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-500 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                Aucune donnée disponible pour le graphique.
                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ResponsiveContainer width="100%" height="100%">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <PieChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Pie
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              data={driverData}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dataKey="value"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nameKey="name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cx="50%"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cy="50%"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  outerRadius={100}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {driverData.map((entry, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Pie>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Tooltip />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Legend />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </PieChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* ====== GRAPHIQUE EN BARRES ====== */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-white rounded-xl shadow p-8 mb-10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-xl font-semibold text-green-700 mb-4 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Évolution des trajets par date
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="h-80">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {ridesByDate.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-500 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Aucune donnée de trajets à afficher.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ResponsiveContainer width="100%" height="100%">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <BarChart data={ridesByDate}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <CartesianGrid strokeDasharray="3 3" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <XAxis dataKey="date" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <YAxis />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Tooltip />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Legend />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Bar dataKey="count" fill="#16a34a" name="Trajets" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </BarChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* ====== DERNIER TRAJET AJOUTÉ ====== */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {lastRide && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-xl shadow p-6 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-xl font-semibold text-green-700 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                🕒 Dernier trajet ajouté
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong>{lastRide.driver}</strong> — {lastRide.depart} → {lastRide.arrivee}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-600 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {lastRide.date} à {lastRide.heure} • {lastRide.prix} €
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
