import { useEffect, useRef, useState } from "react";
import { useFeedbacks } from "../context/FeedbackContext.jsx";

export default function EmployeeDashboard() {
  const { feedbacks, updateFeedbackStatus } = useFeedbacks();

    // 💡 État pour le toast visuel
      const [toast, setToast] = useState(null);
        const previousCount = useRef(feedbacks.length);

          // 🧠 Surveille les nouveaux feedbacks ajoutés
            useEffect(() => {
                if (feedbacks.length > previousCount.current) {
                      const newFb = feedbacks[feedbacks.length - 1];
                            setToast(`🔔 Nouvel avis reçu pour ${newFb.ride}`);
                                  setTimeout(() => setToast(null), 4000);
                                      }
                                          previousCount.current = feedbacks.length;
                                            }, [feedbacks]);

                                              // 📦 Action employé
                                                const handleAction = (id, newStatus) => {
                                                    updateFeedbackStatus(id, newStatus);
                                                        const msg =
                                                              newStatus === "validated"
                                                                      ? "✅ Avis validé avec succès."
                                                                              : newStatus === "rejected"
                                                                                      ? "❌ Avis rejeté."
                                                                                              : "⚠️ Le chauffeur sera contacté.";
                                                                                                  alert(msg);
                                                                                                    };

                                                                                                      return (
                                                                                                          <div className="relative max-w-5xl mx-auto mt-10 p-6 bg-gray-50 rounded-2xl shadow-sm">
                                                                                                                <h2 className="text-3xl font-bold mb-6 text-emerald-600 text-center">
                                                                                                                        Espace Employé 👩‍💼
                                                                                                                              </h2>

                                                                                                                                    {/* 🔔 Notification toast */}
                                                                                                                                          {toast && (
                                                                                                                                                  <div className="fixed top-5 right-5 bg-emerald-600 text-white px-4 py-2 rounded-lg shadow-lg animate-fadeIn">
                                                                                                                                                            {toast}
                                                                                                                                                                    </div>
                                                                                                                                                                          )}

                                                                                                                                                                                {feedbacks.length === 0 ? (
                                                                                                                                                                                        <p className="text-center text-gray-500">
                                                                                                                                                                                                  Aucun avis ou signalement en attente.
                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                        <div className="grid gap-6">
                                                                                                                                                                                                                                  {feedbacks.map((fb) => (
                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                            key={fb.id}
                                                                                                                                                                                                                                                                          className="bg-white border border-gray-200 rounded-xl p-5 shadow"
                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                    <h3 className="font-semibold text-lg mb-1 text-gray-800">
                                                                                                                                                                                                                                                                                                                    🚗 {fb.ride}
                                                                                                                                                                                                                                                                                                                                  </h3>
                                                                                                                                                                                                                                                                                                                                                <p className="text-sm text-gray-600 mb-2">
                                                                                                                                                                                                                                                                                                                                                                <strong>Passager :</strong> {fb.passenger} <br />
                                                                                                                                                                                                                                                                                                                                                                                <strong>Chauffeur :</strong> {fb.driver}
                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                            <p className="italic text-gray-700 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                            « {fb.comment} » ({fb.rating}⭐)
                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        {fb.status === "pending" ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex flex-wrap gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => handleAction(fb.id, "validated")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1 rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ✅ Valider
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => handleAction(fb.id, "rejected")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ❌ Rejeter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => handleAction(fb.id, "contact")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="bg-yellow-400 hover:bg-yellow-500 text-black px-3 py-1 rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ⚠️ Contacter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="mt-2 text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Statut :{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fb.status === "validated"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? "text-emerald-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : fb.status === "rejected"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? "text-red-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : "text-yellow-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {fb.status === "validated"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "Validé"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : fb.status === "rejected"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? "Rejeté"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : "En contact avec le chauffeur"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
