import { useState, useMemo } from "react";
import { useAuth } from "../context/AuthContext.jsx";
import { useUsers } from "../context/UserContext.jsx";

export default function EmployeeManager() {
  const { user } = useAuth(); // utilisateur connecté (doit être admin)
    const { users, addUser, removeUser, updateUserRole } = useUsers();

      const [newEmail, setNewEmail] = useState("");
        const [newRole, setNewRole] = useState("employee");

          // 📊 Calcul des statistiques par rôle
            const stats = useMemo(() => {
                const summary = { admin: 0, employee: 0, driver: 0, passenger: 0 };
                    users.forEach((u) => {
                          if (summary[u.role] !== undefined) summary[u.role]++;
                              });
                                  summary.total = users.length;
                                      return summary;
                                        }, [users]);

                                          // ➕ Ajouter un utilisateur via le contexte global
                                            const handleAddUser = (e) => {
                                                e.preventDefault();
                                                    if (!newEmail.trim()) return alert("Veuillez entrer une adresse email.");

                                                        addUser(newEmail, newRole);
                                                            setNewEmail("");
                                                                setNewRole("employee");
                                                                  };

                                                                    // 🗑️ Supprimer un utilisateur globalement
                                                                      const handleDeleteUser = (email) => {
                                                                          if (email === "admin@ecoride.fr") {
                                                                                alert("⚠️ Vous ne pouvez pas supprimer l’administrateur principal !");
                                                                                      return;
                                                                                          }

                                                                                              if (confirm(`Voulez-vous vraiment supprimer ${email} ?`)) {
                                                                                                    removeUser(email);
                                                                                                        }
                                                                                                          };

                                                                                                            // 🔁 Modifier le rôle d’un utilisateur
                                                                                                              const handleChangeRole = (email, newRole) => {
                                                                                                                  updateUserRole(email, newRole);
                                                                                                                    };

                                                                                                                      // 🚫 Protection si utilisateur non admin
                                                                                                                        if (!user || user.role !== "admin") {
                                                                                                                            return (
                                                                                                                                  <div className="text-center mt-10 text-red-600 font-semibold">
                                                                                                                                          ❌ Accès refusé — réservé à l’administrateur.
                                                                                                                                                </div>
                                                                                                                                                    );
                                                                                                                                                      }

                                                                                                                                                        return (
                                                                                                                                                            <div className="max-w-5xl mx-auto mt-10 p-6 bg-gray-50 rounded-2xl shadow-sm">
                                                                                                                                                                  <h2 className="text-3xl font-bold mb-6 text-emerald-600 text-center">
                                                                                                                                                                          Gestion des utilisateurs 👥
                                                                                                                                                                                </h2>

                                                                                                                                                                                      {/* 📊 Tableau de bord synthétique */}
                                                                                                                                                                                            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
                                                                                                                                                                                                    <StatCard label="Admins" value={stats.admin} color="bg-emerald-600" />
                                                                                                                                                                                                            <StatCard label="Employés" value={stats.employee} color="bg-blue-500" />
                                                                                                                                                                                                                    <StatCard label="Chauffeurs" value={stats.driver} color="bg-orange-500" />
                                                                                                                                                                                                                            <StatCard label="Passagers" value={stats.passenger} color="bg-gray-500" />
                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                        <div className="text-center text-gray-600 mb-6">
                                                                                                                                                                                                                                                <strong>Total utilisateurs :</strong> {stats.total}
                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                            {/* ➕ Formulaire d’ajout */}
                                                                                                                                                                                                                                                                  <form
                                                                                                                                                                                                                                                                          onSubmit={handleAddUser}
                                                                                                                                                                                                                                                                                  className="flex flex-wrap gap-3 mb-6 bg-white border p-4 rounded-xl shadow-sm"
                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                                                                                                    placeholder="Nouvel email..."
                                                                                                                                                                                                                                                                                                                              value={newEmail}
                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setNewEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                  className="flex-grow border rounded-md px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                            <select
                                                                                                                                                                                                                                                                                                                                                                                      value={newRole}
                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setNewRole(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                          className="border rounded-md px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="employee">Employé</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="driver">Chauffeur</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="passenger">Passager</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ➕ Ajouter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* 📋 Tableau des utilisateurs */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="overflow-x-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <table className="min-w-full bg-white border rounded-xl shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr className="bg-emerald-100 text-emerald-800 text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th className="py-2 px-4 border-b">Email</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <th className="py-2 px-4 border-b">Rôle</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th className="py-2 px-4 border-b text-right">Actions</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {users.map((u) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tr key={u.email} className="hover:bg-gray-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="py-2 px-4 border-b">{u.email}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="py-2 px-4 border-b">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={u.role}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => handleChangeRole(u.email, e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="border rounded-md px-2 py-1 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    disabled={u.email === "admin@ecoride.fr"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="admin">Admin</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="employee">Employé</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="driver">Chauffeur</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="passenger">Passager</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td className="py-2 px-4 border-b text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => handleDeleteUser(u.email)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded-md text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={u.email === "admin@ecoride.fr"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            🗑️ Supprimer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 💡 Composant interne : carte statistique stylisée
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function StatCard({ label, value, color }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`${color} text-white rounded-xl p-4 flex flex-col items-center justify-center shadow-md`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-2xl font-bold">{value}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-sm opacity-90">{label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
