export default function Home() {
  return (
      <div className="container mx-auto text-center py-10">
            <h1 className="text-4xl font-bold text-green-700 mb-4">
                    Bienvenue sur EcoRide 🌍
                          </h1>
                                <p className="text-lg text-gray-700 mb-10">
                                        La plateforme de covoiturage écologique et économique.
                                              </p>

                                                    <form
                                                            action="/rides"
                                                                    method="GET"
                                                                            className="flex flex-wrap justify-center gap-3 mb-10"
                                                                                  >
                                                                                          <input
                                                                                                    type="text"
                                                                                                              name="depart"
                                                                                                                        placeholder="Ville de départ"
                                                                                                                                  className="border border-gray-300 rounded px-3 py-2 w-60"
                                                                                                                                            required
                                                                                                                                                    />
                                                                                                                                                            <input
                                                                                                                                                                      type="text"
                                                                                                                                                                                name="arrivee"
                                                                                                                                                                                          placeholder="Ville d'arrivée"
                                                                                                                                                                                                    className="border border-gray-300 rounded px-3 py-2 w-60"
                                                                                                                                                                                                              required
                                                                                                                                                                                                                      />
                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                        type="date"
                                                                                                                                                                                                                                                  name="date"
                                                                                                                                                                                                                                                            className="border border-gray-300 rounded px-3 py-2"
                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                type="submit"
                                                                                                                                                                                                                                                                                                          className="bg-green-600 text-white px-5 py-2 rounded hover:bg-green-700"
                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                            Rechercher
                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                          </form>

                                                                                                                                                                                                                                                                                                                                                <div className="grid md:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                                        <div className="p-5 bg-white rounded shadow">
                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-green-600 text-xl font-semibold mb-2">
                                                                                                                                                                                                                                                                                                                                                                              🌱 Voyagez vert
                                                                                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                                                                                  <p>Partagez vos trajets pour réduire votre empreinte carbone.</p>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-5 bg-white rounded shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-green-600 text-xl font-semibold mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                        �� Faites des économies
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Partagez les frais et profitez de trajets plus abordables.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="p-5 bg-white rounded shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-green-600 text-xl font-semibold mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  🤝 Rejoignez la communauté
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Rencontrez des personnes qui partagent vos valeurs écologiques.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
