import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Login() {
  const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
      const { login } = useAuth();
        const navigate = useNavigate();

          const handleSubmit = (e) => {
              e.preventDefault();
                  // Simulation de connexion (pas de backend)
                      login(email);
                          navigate("/"); // Redirige vers l'accueil
                            };

                              return (
                                  <div className="flex flex-col items-center justify-center min-h-[80vh] bg-green-50">
                                        <div className="bg-white shadow-md rounded-lg p-8 w-full max-w-md">
                                                <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
                                                          Connexion 🔐
                                                                  </h1>

                                                                          <form onSubmit={handleSubmit} className="space-y-4">
                                                                                    <div>
                                                                                                <label className="block text-left text-gray-700 mb-1">
                                                                                                              Email
                                                                                                                          </label>
                                                                                                                                      <input
                                                                                                                                                    type="email"
                                                                                                                                                                  value={email}
                                                                                                                                                                                onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                              placeholder="exemple@mail.com"
                                                                                                                                                                                                            className="w-full border border-gray-300 rounded px-3 py-2 focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                      <label className="block text-left text-gray-700 mb-1">
                                                                                                                                                                                                                                                                                    Mot de passe
                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                          type="password"
                                                                                                                                                                                                                                                                                                                                        value={password}
                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                    placeholder="********"
                                                                                                                                                                                                                                                                                                                                                                                  className="w-full border border-gray-300 rounded px-3 py-2 focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Se connecter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-center text-gray-600 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Pas encore de compte ?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        to="/register"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="text-green-600 hover:underline font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          S'inscrire
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
