import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext.jsx";

/**
 * 🔐 Page de connexion (Login)
  * ----------------------------------------------------
   * Envoie les identifiants (email + mot de passe) vers l’API PHP.
    * Si le backend valide l’utilisateur → stockage dans AuthContext.
     */
     export default function Login() {
       const navigate = useNavigate();
         const { setUser } = useAuth(); // Récupère la fonction pour stocker l'utilisateur
           const [formData, setFormData] = useState({
               email: "",
                   password: "",
                     });

                       const [message, setMessage] = useState("");

                         // 🔁 Gestion des champs de saisie
                           const handleChange = (e) => {
                               setFormData({ ...formData, [e.target.name]: e.target.value });
                                 };

                                   // 🚪 Soumission du formulaire
                                     const handleSubmit = async (e) => {
                                         e.preventDefault();

                                             try {
                                                   const response = await fetch("http://localhost:8000/api/login.php", {
                                                           method: "POST",
                                                                   headers: { "Content-Type": "application/json" },
                                                                           body: JSON.stringify(formData),
                                                                                 });

                                                                                       const data = await response.json();

                                                                                             if (data.status === "success") {
                                                                                                     // ✅ Connexion réussie : on stocke l’utilisateur dans le contexte et le localStorage
                                                                                                             setUser(data.data);
                                                                                                                     localStorage.setItem("user", JSON.stringify(data.data));

                                                                                                                             setMessage("✅ Connexion réussie !");
                                                                                                                                     // 🔀 Redirection selon le rôle
                                                                                                                                             const role = data.data.role;

                                                                                                                                                     setTimeout(() => {
                                                                                                                                                               if (role === "admin") navigate("/admin/dashboard");
                                                                                                                                                                         else if (role === "employee") navigate("/employee/dashboard");
                                                                                                                                                                                   else navigate("/profile");
                                                                                                                                                                                           }, 1500);
                                                                                                                                                                                                 } else {
                                                                                                                                                                                                         setMessage("❌ " + data.message);
                                                                                                                                                                                                               }
                                                                                                                                                                                                                   } catch (err) {
                                                                                                                                                                                                                         setMessage("❌ Erreur de connexion au serveur.");
                                                                                                                                                                                                                               console.error(err);
                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                     };

                                                                                                                                                                                                                                       return (
                                                                                                                                                                                                                                           <div className="flex flex-col items-center justify-center min-h-[80vh] bg-green-50">
                                                                                                                                                                                                                                                 <div className="bg-white shadow-md rounded-lg p-8 w-full max-w-md">
                                                                                                                                                                                                                                                         <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
                                                                                                                                                                                                                                                                   Connexion 🔑
                                                                                                                                                                                                                                                                           </h1>

                                                                                                                                                                                                                                                                                   <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                                                                                                                             {/* --- Email --- */}
                                                                                                                                                                                                                                                                                                       <div>
                                                                                                                                                                                                                                                                                                                   <label className="block text-left text-gray-700 mb-1">Email</label>
                                                                                                                                                                                                                                                                                                                               <input
                                                                                                                                                                                                                                                                                                                                             type="email"
                                                                                                                                                                                                                                                                                                                                                           name="email"
                                                                                                                                                                                                                                                                                                                                                                         placeholder="exemple@mail.com"
                                                                                                                                                                                                                                                                                                                                                                                       value={formData.email}
                                                                                                                                                                                                                                                                                                                                                                                                     onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                   className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                 required
                                                                                                                                                                                                                                                                                                                                                                                                                                             />
                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {/* --- Mot de passe --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <label className="block text-left text-gray-700 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Mot de passe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       placeholder="********"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     value={formData.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {/* --- Bouton de connexion --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 className="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Se connecter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {/* --- Message (succès / erreur) --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <p className="text-center mt-4 text-gray-700 font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {/* --- Lien vers l'inscription --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p className="text-center text-gray-600 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Pas encore de compte ?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 to="/register"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             className="text-green-600 hover:underline font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   S'inscrire
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
