import { useState } from "react";
import { useFeedbacks } from "../context/FeedbackContext.jsx";
import { useAuth } from "../context/AuthContext.jsx";

export default function PassengerRides() {
  const { user } = useAuth();
    const { addFeedback } = useFeedbacks();

      // 🚗 Liste des covoiturages passager
        const [rides, setRides] = useState([
            {
                  id: 1,
                        title: "Paris → Lyon",
                              driver: "admin@ecoride.fr",
                                    date: "21/10/2025",
                                          status: "to_validate",
                                              },
                                                  {
                                                        id: 2,
                                                              title: "Marseille → Nice",
                                                                    driver: "admin@ecoride.fr",
                                                                          date: "19/10/2025",
                                                                                status: "validated",
                                                                                    },
                                                                                      ]);

                                                                                        // 🎯 Données du formulaire d'avis
                                                                                          const [selectedRide, setSelectedRide] = useState(null);
                                                                                            const [rating, setRating] = useState(5);
                                                                                              const [comment, setComment] = useState("");

                                                                                                const handleFeedbackSubmit = (rideId) => {
                                                                                                    if (!comment.trim()) {
                                                                                                          alert("Merci de renseigner un commentaire avant d'envoyer l'avis.");
                                                                                                                return;
                                                                                                                    }

                                                                                                                        // Trouver le covoiturage concerné
                                                                                                                            const ride = rides.find((r) => r.id === rideId);

                                                                                                                                // Ajouter l’avis au contexte global
                                                                                                                                    addFeedback({
                                                                                                                                          ride: ride.title,
                                                                                                                                                passenger: user?.email || "user@ecoride.fr",
                                                                                                                                                      driver: ride.driver,
                                                                                                                                                            rating,
                                                                                                                                                                  comment,
                                                                                                                                                                      });

                                                                                                                                                                          // Mettre à jour le statut du covoiturage
                                                                                                                                                                              setRides((prev) =>
                                                                                                                                                                                    prev.map((r) =>
                                                                                                                                                                                            r.id === rideId ? { ...r, status: "validated" } : r
                                                                                                                                                                                                  )
                                                                                                                                                                                                      );

                                                                                                                                                                                                          // Réinitialiser le formulaire
                                                                                                                                                                                                              setSelectedRide(null);
                                                                                                                                                                                                                  setComment("");
                                                                                                                                                                                                                      setRating(5);

                                                                                                                                                                                                                          alert("✅ Votre avis a été envoyé avec succès !");
                                                                                                                                                                                                                            };

                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                  <div className="max-w-3xl mx-auto mt-8 p-6 bg-gray-50 rounded-2xl shadow-sm">
                                                                                                                                                                                                                                        <h2 className="text-2xl font-bold mb-4 text-emerald-600">
                                                                                                                                                                                                                                                Mes covoiturages passager 🚙
                                                                                                                                                                                                                                                      </h2>

                                                                                                                                                                                                                                                            {rides.map((ride) => (
                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                              key={ride.id}
                                                                                                                                                                                                                                                                                        className="bg-white rounded-xl p-5 mb-4 shadow border border-gray-200"
                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                          <h3 className="text-lg font-semibold text-gray-800 mb-1">
                                                                                                                                                                                                                                                                                                                      {ride.title}
                                                                                                                                                                                                                                                                                                                                </h3>
                                                                                                                                                                                                                                                                                                                                          <p className="text-sm text-gray-600 mb-3">
                                                                                                                                                                                                                                                                                                                                                      Chauffeur : {ride.driver} <br />
                                                                                                                                                                                                                                                                                                                                                                  Date : {ride.date}
                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                      {ride.status === "to_validate" ? (
                                                                                                                                                                                                                                                                                                                                                                                                  selectedRide === ride.id ? (
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-gray-50 p-3 rounded-md border mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Note :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={rating}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setRating(Number(e.target.value))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="border rounded-md px-2 py-1 mb-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {[1, 2, 3, 4, 5].map((n) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option key={n} value={n}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {n} ⭐
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Votre commentaire..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={comment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setComment(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full border rounded-md px-3 py-2 mb-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rows={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => handleFeedbackSubmit(ride.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1 rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ✅ Envoyer l’avis
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setSelectedRide(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="bg-gray-300 hover:bg-gray-400 text-black px-3 py-1 rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ❌ Annuler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => setSelectedRide(ride.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="bg-emerald-500 hover:bg-emerald-600 text-white px-3 py-1 rounded-md"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              📝 Donner mon avis
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-gray-500 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ✅ Avis déjà envoyé et en attente de validation.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
