import { useState, useEffect } from "react";
import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";

export default function Profile() {
  const { user, logout, reservations, cancelReservation } = useAuth();
    const navigate = useNavigate();
      const [formData, setFormData] = useState({ name: "", email: "" });

        // Redirige vers /login si non connecté
          useEffect(() => {
              if (!user) navigate("/login");
                }, [user, navigate]);

                  // Charge les données de l'utilisateur
                    useEffect(() => {
                        if (user) {
                              setFormData({
                                      name: user.name || "",
                                              email: user.email || "",
                                                    });
                                                        }
                                                          }, [user]);

                                                            const handleChange = (e) => {
                                                                setFormData({ ...formData, [e.target.name]: e.target.value });
                                                                  };

                                                                    const handleSave = (e) => {
                                                                        e.preventDefault();
                                                                            const updatedUser = { ...user, ...formData };
                                                                                localStorage.setItem("ecorideUser", JSON.stringify(updatedUser));
                                                                                    alert("✅ Profil mis à jour avec succès !");
                                                                                      };

                                                                                        if (!user) return null;

                                                                                          return (
                                                                                              <div className="flex flex-col items-center justify-center min-h-[80vh] bg-green-50">
                                                                                                    <div className="bg-white shadow-md rounded-lg p-8 w-full max-w-md">
                                                                                                            <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
                                                                                                                      Mon Compte 🌿
                                                                                                                              </h1>

                                                                                                                                      {/* Formulaire du profil */}
                                                                                                                                              <form onSubmit={handleSave} className="space-y-4">
                                                                                                                                                        <div>
                                                                                                                                                                    <label className="block text-left text-gray-700 mb-1">Nom</label>
                                                                                                                                                                                <input
                                                                                                                                                                                              type="text"
                                                                                                                                                                                                            name="name"
                                                                                                                                                                                                                          value={formData.name}
                                                                                                                                                                                                                                        onChange={handleChange}
                                                                                                                                                                                                                                                      placeholder="Votre nom complet"
                                                                                                                                                                                                                                                                    className="w-full border border-gray-300 rounded px-3 py-2 focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                <label className="block text-left text-gray-700 mb-1">Email</label>
                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                                                                                                                                        name="email"
                                                                                                                                                                                                                                                                                                                                                                      value={formData.email}
                                                                                                                                                                                                                                                                                                                                                                                    onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Votre email"
                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full border border-gray-300 rounded px-3 py-2 focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Enregistrer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Section des trajets réservés */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-2xl font-semibold text-green-700 mb-4 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Mes trajets réservés 🚗
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {reservations.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-center text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Vous n'avez encore réservé aucun trajet.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {reservations.map((r) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={r.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="border border-gray-200 rounded p-4 bg-white shadow-sm flex justify-between items-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="font-semibold text-green-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {r.departure} → {r.arrival}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {r.date} — {r.price} €
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => cancelReservation(r.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-red-500 text-white px-3 py-1 rounded hover:bg-red-600 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Annuler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Boutons d'action */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-8 flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={logout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Se déconnecter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => navigate("/")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="bg-gray-300 px-4 py-2 rounded hover:bg-gray-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Retour à l'accueil
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
