import { Link } from "react-router-dom";

export default function Register() {
  return (
      <div className="flex flex-col items-center justify-center min-h-[80vh] bg-green-50">
            <div className="bg-white shadow-md rounded-lg p-8 w-full max-w-md">
                    <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
                              Créer un compte 🌿
                                      </h1>

                                              <form className="space-y-4">
                                                        <div>
                                                                    <label className="block text-left text-gray-700 mb-1">
                                                                                  Nom complet
                                                                                              </label>
                                                                                                          <input
                                                                                                                        type="text"
                                                                                                                                      placeholder="Jean Dupont"
                                                                                                                                                    className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                  required
                                                                                                                                                                              />
                                                                                                                                                                                        </div>

                                                                                                                                                                                                  <div>
                                                                                                                                                                                                              <label className="block text-left text-gray-700 mb-1">
                                                                                                                                                                                                                            Email
                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                  type="email"
                                                                                                                                                                                                                                                                                placeholder="exemple@mail.com"
                                                                                                                                                                                                                                                                                              className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                        <label className="block text-left text-gray-700 mb-1">
                                                                                                                                                                                                                                                                                                                                                                      Mot de passe
                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="********"
                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    S'inscrire
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-center text-gray-600 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Déjà inscrit ?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              to="/login"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="text-green-600 hover:underline font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Se connecter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
