import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

/**
 * 🧩 Page d'inscription (Register)
  * ----------------------------------------------------
   * Permet la création d’un compte utilisateur.
    * À ce stade, elle est prête à être connectée au backend (register.php).
     */
     export default function Register() {
       const navigate = useNavigate();
         const [formData, setFormData] = useState({
             name: "",
                 email: "",
                     password: "",
                       });

                         const [message, setMessage] = useState("");

                           // 🔁 Gère la saisie des champs
                             const handleChange = (e) => {
                                 setFormData({ ...formData, [e.target.name]: e.target.value });
                                   };

                                     // 🧠 Gère la soumission du formulaire
                                       const handleSubmit = async (e) => {
                                           e.preventDefault();

                                               try {
                                                     const response = await fetch("http://localhost:8000/api/register.php", {
                                                             method: "POST",
                                                                     headers: { "Content-Type": "application/json" },
                                                                             body: JSON.stringify(formData),
                                                                                   });

                                                                                         const data = await response.json();

                                                                                               if (data.status === "success") {
                                                                                                       setMessage("✅ Compte créé avec succès !");
                                                                                                               setTimeout(() => navigate("/login"), 1500);
                                                                                                                     } else {
                                                                                                                             setMessage("❌ " + data.message);
                                                                                                                                   }
                                                                                                                                       } catch (error) {
                                                                                                                                             setMessage("❌ Erreur de connexion au serveur.");
                                                                                                                                                   console.error(error);
                                                                                                                                                       }
                                                                                                                                                         };

                                                                                                                                                           return (
                                                                                                                                                               <div className="flex flex-col items-center justify-center min-h-[80vh] bg-green-50">
                                                                                                                                                                     <div className="bg-white shadow-md rounded-lg p-8 w-full max-w-md">
                                                                                                                                                                             <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
                                                                                                                                                                                       Créer un compte 🌿
                                                                                                                                                                                               </h1>

                                                                                                                                                                                                       <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                                                 {/* --- Nom complet --- */}
                                                                                                                                                                                                                           <div>
                                                                                                                                                                                                                                       <label className="block text-left text-gray-700 mb-1">
                                                                                                                                                                                                                                                     Nom complet
                                                                                                                                                                                                                                                                 </label>
                                                                                                                                                                                                                                                                             <input
                                                                                                                                                                                                                                                                                           type="text"
                                                                                                                                                                                                                                                                                                         name="name"
                                                                                                                                                                                                                                                                                                                       placeholder="Jean Dupont"
                                                                                                                                                                                                                                                                                                                                     value={formData.name}
                                                                                                                                                                                                                                                                                                                                                   onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                 className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                               required
                                                                                                                                                                                                                                                                                                                                                                                           />
                                                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                                                               {/* --- Email --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                         <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                     <label className="block text-left text-gray-700 mb-1">Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                 <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                               type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             name="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           placeholder="exemple@mail.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         value={formData.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   {/* --- Mot de passe --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <label className="block text-left text-gray-700 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Mot de passe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         placeholder="********"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       value={formData.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         className="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               S'inscrire
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {/* Message de retour (succès / erreur) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <p className="text-center mt-4 text-gray-700 font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p className="text-center text-gray-600 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Déjà inscrit ?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 to="/login"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             className="text-green-600 hover:underline font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Se connecter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
