import { useState } from "react";
import { rides } from "../data/rides";
import { Link } from "react-router-dom";

export default function Rides() {
  const [departure, setDeparture] = useState("");
    const [arrival, setArrival] = useState("");
      const [date, setDate] = useState("");

        const filteredRides = rides.filter((r) => {
            return (
                  (departure === "" || r.departure.toLowerCase().includes(departure.toLowerCase())) &&
                        (arrival === "" || r.arrival.toLowerCase().includes(arrival.toLowerCase())) &&
                              (date === "" || r.date === date)
                                  );
                                    });

                                      return (
                                          <div className="bg-green-50 min-h-[80vh] py-10">
                                                <div className="container mx-auto text-center px-4">
                                                        <h1 className="text-3xl font-bold text-green-700 mb-6 flex justify-center items-center gap-2">
                                                                  🔍 Rechercher un covoiturage
                                                                          </h1>

                                                                                  {/* 🔎 Barre de recherche */}
                                                                                          <div className="bg-white shadow-md rounded-lg p-6 flex flex-col md:flex-row items-center justify-center gap-4 mb-10 max-w-3xl mx-auto">
                                                                                                    <input
                                                                                                                type="text"
                                                                                                                            placeholder="Départ"
                                                                                                                                        value={departure}
                                                                                                                                                    onChange={(e) => setDeparture(e.target.value)}
                                                                                                                                                                className="border border-gray-300 rounded px-4 py-2 w-full md:w-1/3 focus:ring-2 focus:ring-green-500"
                                                                                                                                                                          />
                                                                                                                                                                                    <input
                                                                                                                                                                                                type="text"
                                                                                                                                                                                                            placeholder="Arrivée"
                                                                                                                                                                                                                        value={arrival}
                                                                                                                                                                                                                                    onChange={(e) => setArrival(e.target.value)}
                                                                                                                                                                                                                                                className="border border-gray-300 rounded px-4 py-2 w-full md:w-1/3 focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                type="date"
                                                                                                                                                                                                                                                                                            value={date}
                                                                                                                                                                                                                                                                                                        onChange={(e) => setDate(e.target.value)}
                                                                                                                                                                                                                                                                                                                    className="border border-gray-300 rounded px-4 py-2 w-full md:w-1/3 focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                              {/* 🧾 Liste des covoiturages */}
                                                                                                                                                                                                                                                                                                                                                      {filteredRides.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                            Aucun covoiturage trouvé pour votre recherche.
                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                    {filteredRides.map((ride) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={ride.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-xl font-semibold text-green-700 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {ride.departure} → {ride.arrival}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-600">📅 {ride.date}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-600">👤 {ride.driver}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-600">💶 {ride.price} €</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-600">💺 {ride.seats} places</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    to={`/rides/${ride.id}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="inline-block bg-green-600 text-white mt-4 px-4 py-2 rounded hover:bg-green-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Voir le détail →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
