import { useState } from "react";
import { Link } from "react-router-dom";
import { rides } from "../data/rides";

export default function Rides() {
  const [search, setSearch] = useState({ depart: "", arrivee: "", date: "" });

    // Gestion du formulaire
      const handleChange = (e) => {
          setSearch({ ...search, [e.target.name]: e.target.value });
            };

              // Filtrage des covoiturages selon les champs saisis
                const filteredRides = rides.filter(
                    (ride) =>
                          (!search.depart ||
                                  ride.departure.toLowerCase().includes(search.depart.toLowerCase())) &&
                                        (!search.arrivee ||
                                                ride.arrival.toLowerCase().includes(search.arrivee.toLowerCase())) &&
                                                      (!search.date || ride.date === search.date)
                                                        );

                                                          return (
                                                              <div className="container mx-auto py-10">
                                                                    {/* Titre principal */}
                                                                          <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
                                                                                  🔍 Rechercher un covoiturage
                                                                                        </h1>

                                                                                              {/* Formulaire de recherche */}
                                                                                                    <form className="flex flex-wrap justify-center gap-3 mb-8">
                                                                                                            <input
                                                                                                                      type="text"
                                                                                                                                name="depart"
                                                                                                                                          value={search.depart}
                                                                                                                                                    onChange={handleChange}
                                                                                                                                                              placeholder="Ville de départ"
                                                                                                                                                                        className="border border-gray-300 rounded px-3 py-2 w-60"
                                                                                                                                                                                />
                                                                                                                                                                                        <input
                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                            name="arrivee"
                                                                                                                                                                                                                      value={search.arrivee}
                                                                                                                                                                                                                                onChange={handleChange}
                                                                                                                                                                                                                                          placeholder="Ville d'arrivée"
                                                                                                                                                                                                                                                    className="border border-gray-300 rounded px-3 py-2 w-60"
                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                              type="date"
                                                                                                                                                                                                                                                                                        name="date"
                                                                                                                                                                                                                                                                                                  value={search.date}
                                                                                                                                                                                                                                                                                                            onChange={handleChange}
                                                                                                                                                                                                                                                                                                                      className="border border-gray-300 rounded px-3 py-2"
                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                    </form>

                                                                                                                                                                                                                                                                                                                                          {/* Résultats */}
                                                                                                                                                                                                                                                                                                                                                {filteredRides.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                        <p className="text-center text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                  Aucun covoiturage trouvé pour votre recherche.
                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                  {filteredRides.map((ride) => (
                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                            key={ride.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                          className="bg-white rounded-lg shadow p-5 hover:shadow-lg transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-green-600 font-bold text-lg mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {ride.departure} → {ride.arrival}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-700">👤 Conducteur : {ride.driver}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-700">📅 Date : {ride.date}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-700">💺 Places : {ride.seats}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-700">💶 Prix : {ride.price} €</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        to={`/rides/${ride.id}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="mt-4 inline-block bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Voir le détail
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
