import { Link, NavLink } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Header() {
  const { user, logout } = useAuth();

    return (
        <header className="bg-white shadow-md sticky top-0 z-50">
              <div className="container mx-auto flex justify-between items-center py-4 px-6">
                      {/* Logo */}
                              <Link to="/" className="text-2xl font-bold text-green-600">
                                        🌿 EcoRide
                                                </Link>

                                                        {/* Navigation */}
                                                                <nav className="flex space-x-6 items-center">
                                                                          <NavLink
                                                                                      to="/"
                                                                                                  className={({ isActive }) =>
                                                                                                                isActive ? "text-green-700 font-semibold" : "hover:text-green-600"
                                                                                                                            }
                                                                                                                                      >
                                                                                                                                                  Accueil
                                                                                                                                                            </NavLink>

                                                                                                                                                                      <NavLink
                                                                                                                                                                                  to="/rides"
                                                                                                                                                                                              className={({ isActive }) =>
                                                                                                                                                                                                            isActive ? "text-green-700 font-semibold" : "hover:text-green-600"
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                              Covoiturages
                                                                                                                                                                                                                                                        </NavLink>

                                                                                                                                                                                                                                                                  <NavLink
                                                                                                                                                                                                                                                                              to="/contact"
                                                                                                                                                                                                                                                                                          className={({ isActive }) =>
                                                                                                                                                                                                                                                                                                        isActive ? "text-green-700 font-semibold" : "hover:text-green-600"
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                          Contact
                                                                                                                                                                                                                                                                                                                                                    </NavLink>

                                                                                                                                                                                                                                                                                                                                                              <NavLink
                                                                                                                                                                                                                                                                                                                                                                          to="/mentions"
                                                                                                                                                                                                                                                                                                                                                                                      className={({ isActive }) =>
                                                                                                                                                                                                                                                                                                                                                                                                    isActive ? "text-green-700 font-semibold" : "hover:text-green-600"
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                      Mentions
                                                                                                                                                                                                                                                                                                                                                                                                                                                </NavLink>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Partie droite : Connexion / Mon compte */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {!user ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <NavLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              to="/login"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={({ isActive }) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isActive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "text-green-700 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "hover:text-green-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Connexion
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </NavLink>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <NavLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        to="/profile"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={({ isActive }) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          isActive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "text-green-700 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : "hover:text-green-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Mon compte
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </NavLink>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-gray-700 font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {user.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={logout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-green-600 text-white px-3 py-1 rounded hover:bg-green-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Déconnexion
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
