import { Link, NavLink } from "react-router-dom";

export default function Header() {
  return (
      <header className="bg-white shadow-md sticky top-0 z-50">
            <div className="container mx-auto flex justify-between items-center py-4 px-6">
                    <Link to="/" className="text-2xl font-bold text-green-600">
                              🌿 EcoRide
                                      </Link>

                                              <nav className="flex space-x-6">
                                                        <NavLink
                                                                    to="/"
                                                                                className={({ isActive }) =>
                                                                                              isActive ? "text-green-700 font-semibold" : "hover:text-green-600"
                                                                                                          }
                                                                                                                    >
                                                                                                                                Accueil
                                                                                                                                          </NavLink>
                                                                                                                                                    <NavLink
                                                                                                                                                                to="/rides"
                                                                                                                                                                            className={({ isActive }) =>
                                                                                                                                                                                          isActive ? "text-green-700 font-semibold" : "hover:text-green-600"
                                                                                                                                                                                                      }
                                                                                                                                                                                                                >
                                                                                                                                                                                                                            Covoiturages
                                                                                                                                                                                                                                      </NavLink>
                                                                                                                                                                                                                                                <NavLink
                                                                                                                                                                                                                                                            to="/contact"
                                                                                                                                                                                                                                                                        className={({ isActive }) =>
                                                                                                                                                                                                                                                                                      isActive ? "text-green-700 font-semibold" : "hover:text-green-600"
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                        Contact
                                                                                                                                                                                                                                                                                                                                  </NavLink>
                                                                                                                                                                                                                                                                                                                                            <NavLink
                                                                                                                                                                                                                                                                                                                                                        to="/login"
                                                                                                                                                                                                                                                                                                                                                                    className={({ isActive }) =>
                                                                                                                                                                                                                                                                                                                                                                                  isActive ? "text-green-700 font-semibold" : "hover:text-green-600"
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                    Connexion
                                                                                                                                                                                                                                                                                                                                                                                                                              </NavLink>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
