import { useState } from "react";

export default function RideFeedbackForm({ ride, onFeedbackSubmit }) {
  const [status, setStatus] = useState(null); // 'ok' ou 'problem'
    const [rating, setRating] = useState(0);
      const [comment, setComment] = useState("");
        const [submitted, setSubmitted] = useState(false);

          const handleSubmit = (e) => {
              e.preventDefault();

                  if (status === "problem" && comment.trim() === "") {
                        alert("Merci d'indiquer un commentaire si le trajet s’est mal passé.");
                              return;
                                  }

                                      const feedback = {
                                            rideId: ride.id,
                                                  status,
                                                        rating: status === "ok" ? rating : null,
                                                              comment,
                                                                  };

                                                                      setSubmitted(true);
                                                                          onFeedbackSubmit(feedback);
                                                                              alert("✅ Merci pour votre retour !");
                                                                                };

                                                                                  if (submitted) {
                                                                                      return (
                                                                                            <div className="p-4 bg-green-50 border border-green-200 rounded-xl text-green-700">
                                                                                                    Merci, votre avis a été soumis.
                                                                                                          </div>
                                                                                                              );
                                                                                                                }

                                                                                                                  return (
                                                                                                                      <form
                                                                                                                            onSubmit={handleSubmit}
                                                                                                                                  className="p-4 bg-white rounded-2xl shadow-sm border space-y-3"
                                                                                                                                      >
                                                                                                                                            <h3 className="font-semibold text-gray-800">
                                                                                                                                                    Évaluer le trajet {ride.title}
                                                                                                                                                          </h3>

                                                                                                                                                                <div className="flex gap-3">
                                                                                                                                                                        <button
                                                                                                                                                                                  type="button"
                                                                                                                                                                                            onClick={() => setStatus("ok")}
                                                                                                                                                                                                      className={`px-3 py-2 rounded-lg ${
                                                                                                                                                                                                                  status === "ok"
                                                                                                                                                                                                                                ? "bg-emerald-500 text-white"
                                                                                                                                                                                                                                              : "bg-gray-100 hover:bg-gray-200"
                                                                                                                                                                                                                                                        }`}
                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                          👍 Tout s’est bien passé
                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                    type="button"
                                                                                                                                                                                                                                                                                                              onClick={() => setStatus("problem")}
                                                                                                                                                                                                                                                                                                                        className={`px-3 py-2 rounded-lg ${
                                                                                                                                                                                                                                                                                                                                    status === "problem"
                                                                                                                                                                                                                                                                                                                                                  ? "bg-red-500 text-white"
                                                                                                                                                                                                                                                                                                                                                                : "bg-gray-100 hover:bg-gray-200"
                                                                                                                                                                                                                                                                                                                                                                          }`}
                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                            👎 Problème rencontré
                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                {status === "ok" && (
                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm text-gray-600 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                              Note du trajet :
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {[1, 2, 3, 4, 5].map((n) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={n}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setRating(n)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={`w-8 h-8 rounded-full ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              n <= rating
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? "bg-yellow-400 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : "bg-gray-200 text-gray-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ★
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm text-gray-600 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {status === "problem"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "Décrivez le problème rencontré :"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : "Commentaire (optionnel) :"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={comment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setComment(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full p-2 border rounded-lg focus:outline-none focus:ring focus:ring-emerald-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rows="3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-emerald-500 text-white px-4 py-2 rounded-xl hover:bg-emerald-600 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Envoyer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
