import { NavLink, Outlet } from "react-router-dom";
import { LayoutDashboard, Users, FileText, LogOut } from "lucide-react";

export default function AdminLayout() {
  return (
      <div className="min-h-screen flex bg-green-50">
            {/* ====== SIDEBAR ====== */}
                  <aside className="w-64 bg-green-700 text-white flex flex-col py-6 px-4 shadow-lg">
                          <h2 className="text-2xl font-bold mb-8 text-center">
                                    🌿 EcoRide Admin
                                            </h2>

                                                    <nav className="flex-1 space-y-2">
                                                              <NavLink
                                                                          to="/admin/dashboard"
                                                                                      className={({ isActive }) =>
                                                                                                    `flex items-center gap-3 px-4 py-2 rounded-lg hover:bg-green-600 transition ${
                                                                                                                    isActive ? "bg-green-600" : ""
                                                                                                                                  }`
                                                                                                                                              }
                                                                                                                                                        >
                                                                                                                                                                    <LayoutDashboard size={18} />
                                                                                                                                                                                Tableau de bord
                                                                                                                                                                                          </NavLink>

                                                                                                                                                                                                    <NavLink
                                                                                                                                                                                                                to="/admin/users"
                                                                                                                                                                                                                            className={({ isActive }) =>
                                                                                                                                                                                                                                          `flex items-center gap-3 px-4 py-2 rounded-lg hover:bg-green-600 transition ${
                                                                                                                                                                                                                                                          isActive ? "bg-green-600" : ""
                                                                                                                                                                                                                                                                        }`
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                          <Users size={18} />
                                                                                                                                                                                                                                                                                                                      Utilisateurs
                                                                                                                                                                                                                                                                                                                                </NavLink>

                                                                                                                                                                                                                                                                                                                                          <NavLink
                                                                                                                                                                                                                                                                                                                                                      to="/admin/logs"
                                                                                                                                                                                                                                                                                                                                                                  className={({ isActive }) =>
                                                                                                                                                                                                                                                                                                                                                                                `flex items-center gap-3 px-4 py-2 rounded-lg hover:bg-green-600 transition ${
                                                                                                                                                                                                                                                                                                                                                                                                isActive ? "bg-green-600" : ""
                                                                                                                                                                                                                                                                                                                                                                                                              }`
                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                <FileText size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Logs système
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </NavLink>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Bouton Déconnexion (optionnel) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button className="flex items-center gap-3 px-4 py-2 rounded-lg hover:bg-green-600 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <LogOut size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Déconnexion
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </aside>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* ====== CONTENU ====== */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <main className="flex-1 p-8 overflow-y-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Outlet /> {/* 🔹 Zone où s’affichent les pages enfants (Dashboard, Users, Logs...) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
