import { useEffect, useState } from "react";
import { Search, ArrowUpDown } from "lucide-react";

export default function Logs() {
  const [logs, setLogs] = useState([]);
    const [filteredLogs, setFilteredLogs] = useState([]);
      const [searchTerm, setSearchTerm] = useState("");
        const [sortOrder, setSortOrder] = useState("desc");
          const [loading, setLoading] = useState(true);
            const [error, setError] = useState(null);

              // 🔹 Charger les logs depuis l’API
                useEffect(() => {
                    const fetchLogs = async () => {
                          try {
                                  const res = await fetch("http://localhost:8000/api/logs.php");
                                          const data = await res.json();
                                                  if (data.success) {
                                                            setLogs(data.logs);
                                                                      setFilteredLogs(data.logs);
                                                                              } else {
                                                                                        setError("Erreur lors du chargement des logs");
                                                                                                }
                                                                                                      } catch (err) {
                                                                                                              setError("Impossible de contacter l’API");
                                                                                                                    } finally {
                                                                                                                            setLoading(false);
                                                                                                                                  }
                                                                                                                                      };
                                                                                                                                          fetchLogs();
                                                                                                                                            }, []);

                                                                                                                                              // 🔎 Filtrage temps réel
                                                                                                                                                useEffect(() => {
                                                                                                                                                    const filtered = logs.filter(
                                                                                                                                                          (log) =>
                                                                                                                                                                  log.user.toLowerCase().includes(searchTerm.toLowerCase()) ||
                                                                                                                                                                          log.action.toLowerCase().includes(searchTerm.toLowerCase()) ||
                                                                                                                                                                                  log.timestamp.toLowerCase().includes(searchTerm.toLowerCase())
                                                                                                                                                                                      );
                                                                                                                                                                                          setFilteredLogs(filtered);
                                                                                                                                                                                            }, [searchTerm, logs]);

                                                                                                                                                                                              // 🔁 Tri par date
                                                                                                                                                                                                const handleSort = () => {
                                                                                                                                                                                                    const sorted = [...filteredLogs].sort((a, b) => {
                                                                                                                                                                                                          const dateA = new Date(a.timestamp);
                                                                                                                                                                                                                const dateB = new Date(b.timestamp);
                                                                                                                                                                                                                      return sortOrder === "asc" ? dateA - dateB : dateB - dateA;
                                                                                                                                                                                                                          });
                                                                                                                                                                                                                              setFilteredLogs(sorted);
                                                                                                                                                                                                                                  setSortOrder(sortOrder === "asc" ? "desc" : "asc");
                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                      if (loading) return <p className="text-center mt-10 text-gray-500">Chargement des logs...</p>;
                                                                                                                                                                                                                                        if (error) return <p className="text-center mt-10 text-red-600">{error}</p>;

                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                              <div className="min-h-[85vh] bg-green-50 py-10">
                                                                                                                                                                                                                                                    <div className="container mx-auto px-6">
                                                                                                                                                                                                                                                            <h1 className="text-3xl font-bold text-green-700 mb-8 text-center">
                                                                                                                                                                                                                                                                      🪵 Journaux MongoDB - Activité du système
                                                                                                                                                                                                                                                                              </h1>

                                                                                                                                                                                                                                                                                      {/* Barre de recherche */}
                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-6">
                                                                                                                                                                                                                                                                                                        <div className="relative w-full max-w-md">
                                                                                                                                                                                                                                                                                                                    <Search className="absolute left-3 top-2.5 text-gray-400" size={20} />
                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                            placeholder="Rechercher un utilisateur, une action, ou une date..."
                                                                                                                                                                                                                                                                                                                                                                          value={searchTerm}
                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setSearchTerm(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Tableau des logs */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-white rounded-xl shadow-md overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <table className="min-w-full text-sm text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <thead className="bg-green-600 text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th className="px-4 py-3">Utilisateur</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th className="px-4 py-3">Action</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th className="px-4 py-3 cursor-pointer" onClick={handleSort}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Date <ArrowUpDown size={16} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {filteredLogs.length > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    filteredLogs.map((log, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tr key={i} className="border-b hover:bg-green-50 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td className="px-4 py-3">{log.user}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td className="px-4 py-3">{log.action}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-4 py-3 text-gray-500">{log.timestamp}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td colSpan="3" className="text-center py-6 text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Aucun log ne correspond à la recherche.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
